### ISSUE TITLE
Project-level configuration file

### ISSUE THREAD

**Issue by nsidnev** [edgedb/edgedb-cli#173]
The continuation of the discussion started at https://github.com/dmgolembiowski/edgemorph/issues/1.

The default path for EdgeDB schemas and migrations may not always be the best solution. At least because of personal preference. 
Yes, now it is possible to specify a custom path to the directory, but using the flag is not very convenient.

How about adding a project level EdgeDB config file? Something like `edgedb.toml`. With the ability to add various parameters there, which can be specified through the CLI flags, perhaps even with support for different environments.

The ability to specify instance name/DSN and the path to the directory with esdl/edgeql files will be especially useful.

```
.
├── app
│   └── __init__.py
├── tests
│   └── __init__.py
├── priv
│   └── edgedb
│       ├── app.esdl
│       └── migrations
├── edgedb.toml
├── poetry.lock
└── pyproject.toml
```

An example content of `edgedb.toml`(the rest of keys that are available through the CLI in the form of flags can also placed here, if necessary):
```toml
[global]
schema_dir = "./priv/edgedb"

[envs.prod]
instance = "production"

[envs.dev]
dsn = "edgedb://localhost/edgedb"
```
